version: "3.8"

services:
  db:
    image: postgres:14.6
    env_file:
      - .env
    volumes:
      - .database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    container_name: rabbitmq
    ports:
        # - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
      - rabbitmq_log:/var/log/rabbitmq/

  # producer container builds the producer image and produces message to the queue
  producer:
    build: producer
    depends_on:
        - rabbitmq
    environment:
        AMQP_URL: 'amqp://rabbitmq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./producer:/usr/src/app/producer
  
  # we spawn 2 consumer containers to run parallely on the same queue
  consumer1:
    build: consumer
    depends_on:
        - rabbitmq
    environment:
        AMQP_URL: 'amqp://rabbitmq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/usr/src/app/consumer

  consumer2:
    build: consumer
    depends_on:
        - rabbitmq
    environment:
        AMQP_URL: 'amqp://rabbitmq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/usr/src/app/consumer

volumes:
    rabbitmq_data:
    rabbitmq_log:
